### ISSUE TITLE
question of test result 

### ISSUE THREAD

**Issue by 972461099** [liqilei/GMFN#4]
hi liqilei,thank you for your outstanding work.
I test my image.the result like this: Edge contours are obvious
How can I do this?
![InkedScreenshot from 2019-12-10 06-37-44_LI](https://user-images.githubusercontent.com/23586956/70413589-b7d5a200-1a92-11ea-9b13-08c9109e0274.jpg)

**Comment by Senwang98** [comment]
@972461099 Can you send this image to me？This is my e-mail address: egqawkq@gmail.com. Thank you very much!

**Comment by 972461099** [comment]
> @972461099 Can you send this image to me？This is my e-mail address: [egqawkq@gmail.com](mailto:egqawkq@gmail.com). Thank you very much!

Sorry,Time has passed too long and the picture is not saved

**Comment by Senwang98** [comment]
Ok, maybe this is a common problem for SR model.

**Comment by liqilei** [comment]
> hi liqilei,thank you for your outstanding work.
> I test my image.the result like this: Edge contours are obvious
> How can I do this?
> ![InkedScreenshot from 2019-12-10 06-37-44_LI](https://user-images.githubusercontent.com/23586956/70413589-b7d5a200-1a92-11ea-9b13-08c9109e0274.jpg)

Sorry for the late reply. Indeed, edge detail missing a common problem for image super-resolution. For, GMFN, our main contribution is the proposed multiple gated feedback module. So we keep other settings (e.g. loss, dataset, optimizor) as the commonly used. If you are interested in improving the corner performance, I recommend this paper.

@InProceedings{wei2020cdc,
  author = {Pengxu Wei, Ziwei Xie, Hannan Lu, ZongYuan Zhan, Qixiang Ye, Wangmeng Zuo, Liang Lin},
  title = {Component Divide-and-Conquer for Real-World Image Super-Resolution},
  booktitle = {Proceedings of the European Conference on Computer Vision},
  year = {2020}
}
