### ISSUE TITLE
How long is the training time?

### ISSUE THREAD

**Issue by Senwang98** [liqilei/GMFN#5]
Can you tell me about the training time? How many 2080ti did you use for training?

**Comment by liqilei** [comment]
Each epoch takes around five minutes.
Only one gpu is used to train.

**Comment by Senwang98** [comment]
This is a bit awkward, because I use two 3090 to train, but one epoch takes about 17 minutes

**Comment by liqilei** [comment]
Maybe you should put your dataset in a SSD.

**Comment by Senwang98** [comment]
okay, thanks for your reply!

**Comment by liqilei** [comment]
You are welcome. When doing experiments, I found hard disk is also important (for iO).
