### ISSUE TITLE
How to reproduce results in your paper?

### ISSUE THREAD

**Issue by Senwang98** [liqilei/GMFN#6]
In order to reproduce the results in your paper, do I only need to prepare training data and then modify the value of scale in json?

**Comment by liqilei** [comment]
No, you don’t. This is the default configuration for the paper.

**Comment by 1187697147** [comment]
Okay, I would also like to ask if I want to reproduce your 2x and 3x results, do I only need to prepare training data and modify the scale(json)?

**Comment by liqilei** [comment]
Yes. You can see more details in SRFBN repo.

**Comment by Senwang98** [comment]
Sorry, there is a problem with my statement, I want to ask how can I reproduce your 2x and 3x results

**Comment by Senwang98** [comment]
ok, thanks again
